### ISSUE TITLE
Saving process for generated data is slow

### ISSUE THREAD

**Issue by ltdeck** [SPL-ethz/snow#38] opened 2022-04-29 15:52 UTC
When saving the pallet files for the 3D model validation, I noticed an excessive runtime for the first set up of data saved, see figure below:

![slowdatasaving](https://user-images.githubusercontent.com/83716040/165979847-728245a1-62fa-483a-8183-436d089d1d6a.PNG)

The issue refers to the current version of the snowfall_validation file. However, I also noticed similar issues before; due to the smaller scale of the box and 2-D shelf simulations, this likely went unnoticed for quite some time.

**Comment by ltdeck** [comment] 2022-04-29 15:53
Labeled as enhancement, since it does not affect the results.

**Comment by ltdeck** [comment] 2022-05-02 13:03
![pallet08_runtime](https://user-images.githubusercontent.com/83716040/166237866-f3450b1b-d48d-4054-ab50-9774e2e150df.PNG)

Saving the pallet simulation (total time 6e6, storage temperature -8°C) required nearly one hour. On the one hand, this is slower than it should be, on the other hand it is not a major issue, compared to the overall computational time (12 h).

**Comment by bizzinho** [comment] 2022-05-02 15:49
hey @ltdeck ; ok, will look into it.

For future reference, please paste code in text form and not as screenshots so I can just copy&paste myself ;) also, the minimum working example I was referencing in slack would imply that I can just copy&paste the entire code into an empty notebook or some such and reproduce the error start to finish. That's what I meant ;)

**Comment by bizzinho** [comment] 2022-05-02 16:24
Now, in general, this might be slow because `numpy.savetext` goes row by row through the array and does the formatting into eng format. This can be helped a bit by specifying a lighter format, such as int (`%i`) which should work just fine for these arrays here. Alternatively, you can cast to pandas dataframe and let use a different method of writing, which is almost as fast as pre-specifying the format:

![image](https://user-images.githubusercontent.com/1315032/166269577-04294f50-76db-438c-8bbf-cb3638c694a5.png)

Of course, I wouldn't necessarily recommend csv for such big files anyway. pickles or a `.npy` format that you get with `numpy.save` might be better in many cases. Since these are basically vectors, there is probably not much to gain from using something entirely different like parquet, feather, etc.

Now as for the slow *first* execution of savetext. I'm not sure, I wasn't able to replicate this with smaller snowflakes (40x40x1). Maybe you can share a full code snippet to reproduce this? Otherwise we can close this issue, as it is more a numpy issue than a snowflake one.

**Comment by ltdeck** [comment] 2022-05-02 16:36
Thanks for looking at it. I prepared a fast sample notebook that you can run right away, needs for me 30s to execute. "validation_snowfall_snow". For me it was 30 times slower to save the first time compared to the next times.

**Comment by ltdeck** [comment] 2022-05-02 16:41
I tested saving the data as integers. It was faster, similar to your case. It did not resolve the general issue, though, of slow times for the first time saving. File sizes indeed are smaller, although we should be careful to use it for the nucleation temperatures.

**Comment by bizzinho** [comment] 2022-05-09 07:13
Hey @ltdeck , I have the suspicion that the problem is actually not `np.savetxt` after all. See below screenshot. Can you try this yourself and confirm?

![image](https://user-images.githubusercontent.com/1315032/167358733-4b5549c3-7f79-4034-8fa4-1c2543f15518.png)

**Comment by bizzinho** [comment] 2022-05-13 15:29
hey @ltdeck , I made a change in a new branch (see 332d25f) that seems to cut the time it takes to compute this in half, can you check it out?

In short, the issue was that the first call to any of these functions in Snowfall was used to build the underlying dataframe containing all the statistics. This was done by iteratively calling the individual `to_frame()` methods of the Snowflakes, which is not the most efficient way of doing things, since there is a lot of repetition (group IDs, vial IDs).

**Comment by ltdeck** [comment] 2022-05-22 14:41
Hey @bizzinho I tested and can confirm that it is indeed faster now. Good job, let's close this issue then.

**Comment by bizzinho** [comment] 2022-05-23 06:08
Requires additional unit tests before it can be marked as completed.

**Closed** 2022-05-24 05:04 UTC
Labels: enhancement
